---
title: "Retrospectiva e plano 2022 ABJ"
subtitle: "<hr/>"
author: "Julio Trecenti e Marcelo Guedes Nunes"
date: "2021-12-17"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["css/xaringan-themer.css", "default"]
    nature:
      ratio: "16:12"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
library(magrittr, include.only = "%>%")

options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  echo=FALSE, 
  warning=FALSE, 
  message=FALSE,
  out.width = "99%", 
  fig.align = "center",
  dpi = 300
)

crop <- function(im, left = 0, top = 0, right = 0, bottom = 0) {
  d <- dim(im[[1]]); w <- d[2]; h <- d[3]
  magick::image_crop(
    im, 
    glue::glue("{w-left-right}x{h-top-bottom}+{left}+{top}")
  )
}

```


class: center,middle,inverse

# Parcerias

---

# Parcerias

<hr/>

## USP-EACH: process mining

## Unichristus: Judicialização da Saúde

## DREI - ME

---
class: center,middle,inverse

# Projetos

---

# Projetos

<hr/>

## BID - Tributário

## Observatórios

### Falências - SP

### Mercado de Capitais

### Societário

### Recuperações Judiciais - SP, RJ, RS


---
class: center,middle,inverse

# Ensino / pesquisa

---

# Ensino / pesquisa

<hr/>

## Novo curso de Jurimetria na PUC-SP

https://ndtj.com.br

## Atendimentos a pesquisadores

---
class: center,middle,inverse

# Pesquisa e desenvolvimento

---
# Pesquisa e desenvolvimento

<hr/>

## Dashboard de associados

## Atualizações no site

## Reestruturação interna (tarefas, códigos, projetos etc)

## Melhoria de nossos pacotes

---
class: center,middle,inverse

# Plano 2022

---

# Plano 2022

<hr/>

## Observatório da Litigiosidade

## Observatório da Arbitragem

## Recuperações Judiciais - RJ - Fase 2

## Mercado de Capitais - Fase 2

## ...

---
class: center,middle


# Sugestões?